#!/bin/bash
# Build ClaudeRemote.ipa for AltStore sideloading
#
# Prerequisites:
#   1. Xcode installed from App Store (not just Command Line Tools)
#   2. Open project in Xcode once first: open ClaudeRemote.xcodeproj
#      This auto-creates the scheme needed for archiving.
#   3. In Xcode → Signing & Capabilities → set Team to your Apple ID
#
# Usage:
#   ./build-for-altstore.sh              # builds Release .ipa
#   ./build-for-altstore.sh debug        # builds Debug .ipa
#
# The resulting .ipa will be in ./build/ClaudeRemote.ipa
# Transfer it to iPhone via AirDrop, Files, or any file sharing method.
# Then in AltStore → My Apps → + → select the .ipa

set -euo pipefail
cd "$(dirname "$0")"

CONFIG="${1:-release}"
OUTDIR="./build"
ARCHIVE="$OUTDIR/ClaudeRemote.xcarchive"
IPA="$OUTDIR/ClaudeRemote.ipa"

# ── Colors ────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }

# ── Check prerequisites ───────────────────────────────────────────
check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        err "$1 not found. $2"
        exit 1
    fi
}

check_cmd xcodebuild "Install Xcode from the App Store: https://apps.apple.com/app/xcode/id497799835"

# Verify it's actual Xcode, not just CLT
if ! xcodebuild -version 2>&1 | grep -q "Xcode"; then
    err "Xcode Command Line Tools detected, but full Xcode is required."
    echo "   Run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer"
    exit 1
fi

# ── Verify project opens in Xcode ─────────────────────────────────
if [ ! -d "ClaudeRemote.xcodeproj" ]; then
    err "ClaudeRemote.xcodeproj not found. Run: python3 gen-xcode.py"
    exit 1
fi

info "Building $CONFIG configuration..."

# ── Clean ─────────────────────────────────────────────────────────
rm -rf "$OUTDIR"
mkdir -p "$OUTDIR"

# ── Determine scheme ──────────────────────────────────────────────
# Scheme is auto-generated by Xcode when project is first opened.
# Default scheme name matches target name.
SCHEME="ClaudeRemote"

info "Archiving (this may take a few minutes)..."
xcodebuild archive \
    -project ClaudeRemote.xcodeproj \
    -scheme "$SCHEME" \
    -configuration "$CONFIG" \
    -archivePath "$ARCHIVE" \
    -destination "generic/platform=iOS" \
    -allowProvisioningUpdates \
    -showBuildTimingSummary \
    2>&1 | grep -E "(^\\*\\*|error:|warning:|BUILD|ARCHIVE)" || true

ARCHIVE_EXIT=${PIPESTATUS[0]}

if [ $ARCHIVE_EXIT -ne 0 ]; then
    err "Archive failed (exit code $ARCHIVE_EXIT)"
    echo ""
    echo "Troubleshooting:"
    echo "  1. Open project in Xcode first:  open ClaudeRemote.xcodeproj"
    echo "  2. Set signing team:  Xcode → ClaudeRemote target → Signing → Team"
    echo "  3. Try building in Xcode with Cmd+B first to verify"
    exit $ARCHIVE_EXIT
fi

info "Archive created: $ARCHIVE"

# ── Export IPA ─────────────────────────────────────────────────────
info "Exporting .ipa..."

xcodebuild -exportArchive \
    -archivePath "$ARCHIVE" \
    -exportPath "$OUTDIR" \
    -exportOptionsPlist ExportOptions.plist \
    -allowProvisioningUpdates \
    2>&1 | grep -E "(error:|warning:|EXPORT|Success)" || true

EXPORT_EXIT=${PIPESTATUS[0]}

if [ $EXPORT_EXIT -ne 0 ]; then
    err "Export failed (exit code $EXPORT_EXIT)"
    exit $EXPORT_EXIT
fi

# ── Result ─────────────────────────────────────────────────────────
if [ -f "$IPA" ]; then
    IPA_SIZE=$(du -h "$IPA" | cut -f1)
    echo ""
    info "=============================================="
    info "  IPA ready: $IPA ($IPA_SIZE)"
    info "=============================================="
    echo ""
    echo "Next steps:"
    echo "  1. Transfer .ipa to your iPhone:"
    echo "     • AirDrop:  open build/"
    echo "     • Or use:   scp build/ClaudeRemote.ipa mobile@<iphone-ip>:"
    echo ""
    echo "  2. On iPhone → AltStore → My Apps → + → select ClaudeRemote.ipa"
    echo ""
    echo "  Note: AltStore re-signs with your Apple ID cert."
    echo "        The app is valid for 7 days, then AltStore auto-refreshes."
else
    err "IPA not found at $IPA"
    echo "Check $OUTDIR for exported files."

    # Try to find any .ipa
    FOUND=$(find "$OUTDIR" -name "*.ipa" 2>/dev/null)
    if [ -n "$FOUND" ]; then
        echo "Found: $FOUND"
    fi
    exit 1
fi
